### ISSUE TITLE
V 3.1.0: Minor debugger improvements?

### ISSUE THREAD

**Issue by fade2gray** [vscode-autohotkey/ahkpp#279]
Ref: #275

As soon as I run the debugger, the console opens with...
`C:/Program Files/AutoHotkey/AutoHotkeyU64.exe /ErrorStdOut /debug=localhost:9000 c:\Users\fade2gray\Desktop\ahk\test.ahk`

If I close the console and then attempt to close the debugger with either `Ctrl+F5` or the red button, the console reopens to inform that `The debugger has stopped`; I then have to use `Ctrl+F5` or the red button again to close the debugger.

This wasn't an issue pre 3.1.0.

**Comment by mark-wiemer** [comment]
Hey @fade2gray, I'm not able to repro this. I am able to debug this script and stop it with `Shift+F5` and the red square consistently, even when the output console is closed.

In this repro video, I typed ctrl+F5 but it turns out "stop debugging" is bound to shift+f5 for me. Could this be the issue?

If you can, I've found Windows Game Bar + OneDrive to be a super easy way to share screen recordings.

Here is the script I ran:

```ahk
; Select the following line and hit `Ctrl + F8` to run selection
f1:: MsgBox, You hit F1

; The F2 hotkey will not work because it was not part of the selection
f2:: MsgBox, You hit F2
```

And [here's me debugging it](https://1drv.ms/v/s!AjpvI1edrtIploRiHAE-BQ0gn2iVQg?e=yUhp1M)

Some thoughts:

1. Could you have other extensions interfering? AHK+ or the other AHK debugger?
2. Are your keybindings correct?

**Comment by fade2gray** [comment]
Hi Mark, my mistake, the keybinding is `Shift+F5` and not `Ctrl+F5` as first stated.

I see exactly the same behaviour as in your video when running the debugger with your example script, but this is what I see when running a simple script with a breakpoint.

https://user-images.githubusercontent.com/1332009/204086094-eef842a2-5f8b-4775-9e0f-fc846f773797.mp4

**Comment by mark-wiemer** [comment]
OK, thanks for this great repro video! I should have this one fixed in a few days. Testing debugger changes is difficult due to some VS Code issues -- I have to "debug" the new code itself and then run a debugger against that, and VS Code doesn't like doing that :P otherwise it looks like a simple change and we have the v3.0 code to compare against. Thanks again for this report!

@fade2gray, can I ask what software you're using to record your screen?

**Comment by fade2gray** [comment]
Screen recorder: a very old version (11, possibly 2011) of TechSmith Snagit.

Whilst on the subject of the debugger, would it be possible to add an options setting to suppress the console altogether, I seem to remember some asking a similar question a few years back - may have been in AHK plus?

**Comment by mark-wiemer** [comment]
#70, perhaps? Anyway, sorry I haven't gotten to this one yet. Most of my time on this project is spent improving the engineering quality of life so I can review changes from other folks. Thanks for your patience.
