### ISSUE TITLE
Object's continuation section: no indent for code after object

### ISSUE THREAD

**Issue by kyklish** [vscode-autohotkey/ahkpp#310]
### Description

We have 2 open braces, but `code` indented only by one level.

### Expected formatted output snippet

```autohotkey
{
    obj := {
        , {
            , } ; user forgot close brace
        code
}
```

### Actual formatted output snippet

```autohotkey
{
    obj := {
        , {
            , }
    code
}
```

**Comment by mark-wiemer** [comment]
In general, I don't want to worry about how the formatter behaves when given a syntactically incorrect file. If the file doesn't compile, our formatter shouldn't change it at all. If the user enters the wrong number of braces, we should show the red squiggly instead of relying on our formatter to indicate the error -- after all, some users may not use the formatter at all.

**Comment by mark-wiemer** [comment]
Hey @kyklish, let's discuss the bug here and leave the PR discussion for implementation details :)

RE your response on the PR (#311):

> @mark-wiemer, in bug issue I describe only visible part of this PR. This PR fix critical bug: formatter must reset flag openBraceObjectDepth = -1;, when it meets end of object's continuation section. It will do, when syntax is correct (num of open brace equal num of close brace), but it does not, when num of close brace is less.
>
> From my point of view "Every Curvy Brace Is Matter". If I have more open brace in broken code, then code must be indented, if less - unindented. Now, it's strange behavior of formatter, it unresponsive for close brace in continuation section.
>
> Recently I wrote script with more than 1k lines with huge object (it has three level of nesting), I had one close brace less and I spend 30 minutes to count all braces, checking all nestings, etc, because I was sure, if code formatted well, than number of curve braces is ok. But it was not.

Are you not able to reference VS Code's [bracket pair colorization](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization) for this?

![image](https://user-images.githubusercontent.com/7833360/213179603-a60d690b-184e-4543-9172-2d376056ad90.png)

Note the unmatched brackets will always be red.

Again, I definitely recognize that work needs to be done here to resolve the general issue of "users can't identify unmatched braces", but I think the best work to do is to update the syntax highlighter to add a red squiggly under unmatched sections of code that won't syntactically compile.

Adding more code to the formatter is a possible workaround, but it'd only further clutter an already huge function.

**Comment by kyklish** [comment]
Let's forget about the wrong syntax.

Do we have any style rules for formatting code? I think we do. One of them is the open\close curly braces: increase\decrease indentation level when we hit it in code. It doesn't matter where or when, always, except for strings and comments.

Current formatter follow this rule only 99% of the time. We leave that 1% of undefined behavior.... out of scope.

I feel that this is a mistake, and I have no further arguments. I accept your final decision and will not argue about it anymore :)
